services:
  curriculum:
    image: rubenag83/curriculum-ia
    build:
      context: .
      platforms:
        - "linux/amd64"
    ports:
      - "5080:80"

  reverse-proxy:
    image: valian/docker-nginx-auto-ssl:1.0.0
    container_name: reverse-proxy
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./.ssl-data:/etc/resty-auto-ssl
    environment:
      ALLOWED_DOMAINS: "rubenalvarezgonzalez.eu;localhost"
      SITES: "rubenalvarezgonzalez.eu=curriculum:80;localhost=curriculum:80"
      FORCE_HTTPS: "true"
    depends_on:
      - curriculum

volumes:
  .ssl-data:
