services:
  curriculum:
    image: rubenag83/curriculum-ia
    build:
      context: .
      platforms:
        - "linux/amd64"
    ports:
      - "5080:80"

  reverse-proxy:
    image: nginx:stable-perl
    container_name: reverse-proxy
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./.ssl-data:/etc/nginx/certs
      - ./nginx/nginx-reverse.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - curriculum

volumes:
  .ssl-data:
  nginx:
